# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
