# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review_app', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_id',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
